# tasks file for Capstone
- name: install python
  apt:
    name: python3
    state: present

- name: Install boto for AWS
  pip:
    name: "{{ item }}"
    state: present
  with_items:
  - boto
  - boto3

- name: Creating Security Group for K8s Cluster
  ec2_group:
    name: '{{ sg_name }}'
    description: Security Group for allowing all port
    region: '{{ region_name }}'
    aws_access_key: '{{ access_key }}'
    aws_secret_key: '{{ secret_key }}'
    rules:
      - proto: all
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

- name: create a new ec2 key
  ec2_key:
    name: ansible
    region: "{{ region }}"
    aws_access_key: '{{ access_key }}'
    aws_secret_key: '{{ secret_key }}'
    state: present
  register: ec2_key

- name: Save private key to disk
  copy: content="{{ ec2_key.key.private_key }}" dest="./ansible.pem" mode=0600
  when: ec2_key.changed

- name: Launching three EC2 instances on AWS
  ec2:
    key_name: '{{ keypair }}'
    instance_type: '{{ instance_flavour }}'
    image: '{{ ami_id }}'
    wait: true
    group: '{{ sg_name }}'
    count: 1
    vpc_subnet_id: '{{ subnet_name }}'
    assign_public_ip: yes
    region: '{{ region_name }}'
    state: present
    aws_access_key: '{{ access_key }}'
    aws_secret_key: '{{ secret_key }}'
    instance_tags:
      Name: '{{ item }}'
  register: ec2
  loop: '{{ instance_tag }}'

- set_fact:
    id: "{{ id + item['instance_ids'] }}"
  with_items:
    - "{{ ec2.results }}"

- include_tasks: elb.yml

- name: Add 1st instance to host group ec2_master
  add_host:
    hostname: '{{ ec2.results[0].instances[0].public_ip }}'
    groupname: ec2_master

- name: Add 2nd instance to host group ec2_worker
  add_host:
    hostname: '{{ ec2.results[1].instances[0].public_ip }}'
    groupname: ec2_worker

- name: Add 3rd instance to host group ec2_worker
  add_host:
    hostname: '{{ ec2.results[2].instances[0].public_ip }}'
    groupname: ec2_worker

- name: Wait for SSH to come up
  wait_for:
    host: '{{ ec2.results[2].instances[0].public_dns_name }}'
    port: 22
    state: started