
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sha-rolebinding
  namespace: dev
subjects:
- kind: User
  name: sha
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io
