- hosts: localhost
  gather_facts: no
  vars_files:
    - cred.yml
  tasks:
    - name: Running EC2 Role
      include_role:
        name: aws_ec2_elb

- hosts: ec2_master
  gather_facts: no
  become: true
  tasks:
    - name: Running K8s Master Role
      include_role:
        name: kubernetes_master

- hosts: ec2_worker
  gather_facts: no
  become: true
  tasks:
    - name: Running K8s Worker Role
      include_role:
        name: kubernetes_nodes

- hosts: ec2_master
  gather_facts: no
  become: true
  tasks:
  name: Apply yaml  to the cluster.
  community.kubernetes.k8s:
    state: present
    src: "{{ item }}"
  with_items:
    - apache.yaml
    - frontend_deployment.yaml
    - frontend_node.yaml
    - metrics.yaml
    - php.yaml
    - redis_followers.yaml
    - redis_leader.yaml