- name: create user
  shell: echo "Y" | sudo adduser sha --disabled-password
- name: rights for user
  command: usermod -aG sudo sha
- name: Add devops user to the sudoers
  copy:
    dest: "/etc/sudoers.d/sha"
    content: "sha  ALL=(ALL)  NOPASSWD: ALL"

